CREATE TABLE PERSONA(
	cod_persona NUMBER  GENERATED BY DEFAULT ON NULL AS IDENTITY, 
	tipo_documento varchar(2),
	documento number,
	primer_nombre varchar2(30),
	segundo_nombre varchar2(30),
	primer_apellido varchar2(30),
	segundo_apellido varchar2(30),
	celular varchar2(10),
	direccion varchar2(200),
	email varchar2(100),
	tipo varchar(10),
	estado NUMBER(1)
);

CREATE TABLE MARCAS(
	cod_marca NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
	nombre_marca varchar2(30)
);

CREATE TABLE VEHICULOS(
	placa varchar2(6),
	color varchar(30),
	fk_cod_marca NUMBER,
	fk_cod_cliente NUMBER,
	CONSTRAINT VEHICULOS_MARCAS FOREIGN KEY (fk_cod_marca) REFERENCES  MARCAS(cod_marca),
	CONSTRAINT VEHICULOS_CLIENTE FOREIGN KEY (fk_cod_cliente) REFERENCES  PERSONA(cod_persona)
);

CREATE TABLE MANTENIMIENTOS(
	cod_mantenimiento NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
	estado varchar(20),
	fk_vehiculo varchar(6),
	fecha DATE ,
	fk_persona_mecanico NUMBER,
	CONSTRAINT MANTENIMIENTO_MECANICO_PERSONA FOREIGN KEY (fk_persona_mecanico) REFERENCES PERSONA(cod_persona),
	CONSTRAINT MANTENIMIENTO_FK_VEHICULO FOREIGN KEY (fk_vehiculo) REFERENCES VEHICULOS(placa)

);

CREATE TABLE FOTOS(
	cod_fotos NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
	ruta varchar(200),
	cod_mantenimiento NUMBER,
	CONSTRAINT FOTOS_MANTENIMIENTO FOREIGN KEY (cod_mantenimiento) REFERENCES MANTENIMIENTO(cod_mantenimiento)
);


CREATE TABLE SERVICIOS(
	cod_servicio NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
	numbre_servicio varchar2(100),
	precio NUMBER	
);

CREATE TABLE SERVICIOS_MANTENIMIENTO(
	cod_smante NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
	tiempo_estimado NUMBER ,
	fk_cod_servicio NUMBER,
	fk_cod_mantenimiento NUMBER,
	CONSTRAINT SERV_MANTEN_COD_SER FOREIGN KEY (fk_cod_servicio) REFERENCES  SERVICIOS(cod_servicio),
	CONSTRAINT SERV_SER_COD_MANTENI FOREIGN KEY (fk_cod_mantenimiento) REFERENCES MANTENIMIENTOS(cod_mantenimiento)	
);

CREATE TABLE REPUESTOS(
	cod_repuesto NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
	numbre_repuesto varchar2(100),
	precio_unitario NUMBER,
	unidades_inventario NUMBER,
	proveedor varchar(200)
);

CREATE TABLE REPUESTOS_MANTENIMIENTO(
	cod_rmante NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
	unidades NUMBER ,
	tiempo_estimado NUMBER,
	fk_cod_repuesto NUMBER,
	fk_cod_mantenimiento NUMBER,
	CONSTRAINT REPU_MANTEN_COD_SER FOREIGN KEY (fk_cod_repuesto) REFERENCES  REPUESTOS(cod_repuesto),
	CONSTRAINT REPU_SER_COD_MANTENI FOREIGN KEY (fk_cod_mantenimiento) REFERENCES MANTENIMIENTOS(cod_mantenimiento)	
);



